---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  namespace: cst8918
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  # This is the pod template
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app-container
          # this is the Docker image that you created
          image: yvanniyonzima/cst8918-a01-weather-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: api-key